#include "teapot.h"
#include "teapot_data.h"

Teapot::Teapot()
{
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 12, GL_UNSIGNED_SHORT, 0));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 78, GL_UNSIGNED_SHORT, 12));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 35, GL_UNSIGNED_SHORT, 90));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 70, GL_UNSIGNED_SHORT, 125));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 65, GL_UNSIGNED_SHORT, 195));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 37, GL_UNSIGNED_SHORT, 260));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 35, GL_UNSIGNED_SHORT, 297));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 32, GL_UNSIGNED_SHORT, 332));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 56, GL_UNSIGNED_SHORT, 364));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 45, GL_UNSIGNED_SHORT, 420));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 41, GL_UNSIGNED_SHORT, 465));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 37, GL_UNSIGNED_SHORT, 506));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 33, GL_UNSIGNED_SHORT, 543));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 29, GL_UNSIGNED_SHORT, 576));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 25, GL_UNSIGNED_SHORT, 605));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 21, GL_UNSIGNED_SHORT, 630));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 17, GL_UNSIGNED_SHORT, 651));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 13, GL_UNSIGNED_SHORT, 668));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 9, GL_UNSIGNED_SHORT, 681));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 27, GL_UNSIGNED_SHORT, 690));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 16, GL_UNSIGNED_SHORT, 717));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 22, GL_UNSIGNED_SHORT, 733));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 50, GL_UNSIGNED_SHORT, 755));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 42, GL_UNSIGNED_SHORT, 805));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 43, GL_UNSIGNED_SHORT, 847));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 4, GL_UNSIGNED_SHORT, 890));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 143, GL_UNSIGNED_SHORT, 894));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 234, GL_UNSIGNED_SHORT, 1037));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 224, GL_UNSIGNED_SHORT, 1271));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 71, GL_UNSIGNED_SHORT, 1495));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 69, GL_UNSIGNED_SHORT, 1566));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 67, GL_UNSIGNED_SHORT, 1635));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 65, GL_UNSIGNED_SHORT, 1702));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 63, GL_UNSIGNED_SHORT, 1767));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 61, GL_UNSIGNED_SHORT, 1830));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 59, GL_UNSIGNED_SHORT, 1891));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 57, GL_UNSIGNED_SHORT, 1950));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 55, GL_UNSIGNED_SHORT, 2007));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 53, GL_UNSIGNED_SHORT, 2062));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 51, GL_UNSIGNED_SHORT, 2115));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 2166));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 50, GL_UNSIGNED_SHORT, 2169));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 48, GL_UNSIGNED_SHORT, 2219));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 46, GL_UNSIGNED_SHORT, 2267));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 44, GL_UNSIGNED_SHORT, 2313));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 42, GL_UNSIGNED_SHORT, 2357));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 40, GL_UNSIGNED_SHORT, 2399));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 38, GL_UNSIGNED_SHORT, 2439));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 36, GL_UNSIGNED_SHORT, 2477));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 34, GL_UNSIGNED_SHORT, 2513));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 32, GL_UNSIGNED_SHORT, 2547));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 30, GL_UNSIGNED_SHORT, 2579));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 28, GL_UNSIGNED_SHORT, 2609));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 26, GL_UNSIGNED_SHORT, 2637));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 24, GL_UNSIGNED_SHORT, 2663));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 22, GL_UNSIGNED_SHORT, 2687));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 20, GL_UNSIGNED_SHORT, 2709));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 18, GL_UNSIGNED_SHORT, 2729));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 16, GL_UNSIGNED_SHORT, 2747));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 14, GL_UNSIGNED_SHORT, 2763));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 12, GL_UNSIGNED_SHORT, 2777));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 10, GL_UNSIGNED_SHORT, 2789));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 8, GL_UNSIGNED_SHORT, 2799));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 6, GL_UNSIGNED_SHORT, 2807));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 2813));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 2816));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 200, GL_UNSIGNED_SHORT, 2819));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 3019));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 66, GL_UNSIGNED_SHORT, 3022));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 3088));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 209, GL_UNSIGNED_SHORT, 3091));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 3300));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 3303));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 3306));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 38, GL_UNSIGNED_SHORT, 3309));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 15, GL_UNSIGNED_SHORT, 3347));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 3362));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 26, GL_UNSIGNED_SHORT, 3365));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 9, GL_UNSIGNED_SHORT, 3391));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 3400));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 14, GL_UNSIGNED_SHORT, 3403));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 3417));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 115, GL_UNSIGNED_SHORT, 3420));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 3535));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 3538));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 39, GL_UNSIGNED_SHORT, 3541));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 3580));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 91, GL_UNSIGNED_SHORT, 3583));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 3674));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 3677));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 31, GL_UNSIGNED_SHORT, 3680));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 3711));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 67, GL_UNSIGNED_SHORT, 3714));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 3781));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 3784));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 23, GL_UNSIGNED_SHORT, 3787));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 3810));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 45, GL_UNSIGNED_SHORT, 3813));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 3858));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 3861));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 3864));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 32, GL_UNSIGNED_SHORT, 3867));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 38, GL_UNSIGNED_SHORT, 3899));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 15, GL_UNSIGNED_SHORT, 3937));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 3952));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 26, GL_UNSIGNED_SHORT, 3955));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 9, GL_UNSIGNED_SHORT, 3981));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 3990));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 14, GL_UNSIGNED_SHORT, 3993));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 4007));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 135, GL_UNSIGNED_SHORT, 4010));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 4145));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 76, GL_UNSIGNED_SHORT, 4148));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 4224));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 60, GL_UNSIGNED_SHORT, 4227));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 4287));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 23, GL_UNSIGNED_SHORT, 4290));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 4313));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 26, GL_UNSIGNED_SHORT, 4316));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 4342));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 6, GL_UNSIGNED_SHORT, 4345));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 947, GL_UNSIGNED_SHORT, 4351));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 35, GL_UNSIGNED_SHORT, 5298));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 31, GL_UNSIGNED_SHORT, 5333));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 27, GL_UNSIGNED_SHORT, 5364));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 23, GL_UNSIGNED_SHORT, 5391));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 20, GL_UNSIGNED_SHORT, 5414));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 24, GL_UNSIGNED_SHORT, 5434));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 5458));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 28, GL_UNSIGNED_SHORT, 5461));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 32, GL_UNSIGNED_SHORT, 5489));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 36, GL_UNSIGNED_SHORT, 5521));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 76, GL_UNSIGNED_SHORT, 5557));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 5633));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 67, GL_UNSIGNED_SHORT, 5636));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 5703));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 59, GL_UNSIGNED_SHORT, 5706));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 5765));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 51, GL_UNSIGNED_SHORT, 5768));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 5819));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 43, GL_UNSIGNED_SHORT, 5822));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 5865));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 35, GL_UNSIGNED_SHORT, 5868));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 5903));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 27, GL_UNSIGNED_SHORT, 5906));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 5933));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 19, GL_UNSIGNED_SHORT, 5936));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 5955));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 11, GL_UNSIGNED_SHORT, 5958));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 5969));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 30, GL_UNSIGNED_SHORT, 5972));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 6002));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 11, GL_UNSIGNED_SHORT, 6005));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 18, GL_UNSIGNED_SHORT, 6016));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 6034));
	primitives_.emplace_back(Primitive(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, 6037));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 5, GL_UNSIGNED_SHORT, 6040));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 122, GL_UNSIGNED_SHORT, 6045));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 75, GL_UNSIGNED_SHORT, 6167));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 71, GL_UNSIGNED_SHORT, 6242));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 67, GL_UNSIGNED_SHORT, 6313));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 63, GL_UNSIGNED_SHORT, 6380));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 59, GL_UNSIGNED_SHORT, 6443));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 55, GL_UNSIGNED_SHORT, 6502));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 51, GL_UNSIGNED_SHORT, 6557));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 47, GL_UNSIGNED_SHORT, 6608));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 43, GL_UNSIGNED_SHORT, 6655));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 39, GL_UNSIGNED_SHORT, 6698));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 35, GL_UNSIGNED_SHORT, 6737));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 31, GL_UNSIGNED_SHORT, 6772));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 27, GL_UNSIGNED_SHORT, 6803));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 23, GL_UNSIGNED_SHORT, 6830));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 19, GL_UNSIGNED_SHORT, 6853));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 15, GL_UNSIGNED_SHORT, 6872));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 11, GL_UNSIGNED_SHORT, 6887));
	primitives_.emplace_back(Primitive(GL_TRIANGLE_STRIP, 7, GL_UNSIGNED_SHORT, 6898));

	int vertices_size = sizeof(teapotVertices);
	vertices_ = (GLfloat*)new char[vertices_size];
	memcpy(vertices_, teapotVertices, vertices_size);

	vertice_count_ = vertices_size / sizeof(GLfloat);

	int normal_size = sizeof(teapotNormals);
	normals_ = (GLfloat*)new char[normal_size];
	memcpy(normals_, teapotNormals, normal_size);

	normal_count_ = normal_size / sizeof(GLfloat);

	int indices_size = sizeof(teapotIndices);
	indices_ = (GLushort*)new char[indices_size];
	memcpy(indices_, teapotIndices, indices_size);

	indice_count_ = sizeof(teapotIndices) / sizeof(GLushort);
}

Teapot::~Teapot()
{
	delete[] vertices_;
	delete[] normals_;
}

